export type Zero = 0 | -0; // NOTE: Typescript resolves `-0` to `0` but is included in this type anyways
export type Integer<T extends number> = `${T}` extends `${infer V extends number}.${string}` ? V : T;
export type Positive<T extends number> = T extends 0 | -0 ? 0 : `${T}` extends `-${infer V extends number}` ? V : T;
export type IsPositive<T extends number> = T extends Positive<T> ? true : false;
export type Negative<T extends number> = T extends 0 | -0 ? -0 : `-${T}` extends `${infer N extends number}` ? N : T;
export type IsNegative<T extends number> = T extends Negative<T> ? true : false;
export type PositiveInteger<T extends number> = Integer<Positive<T>>;
export type NegativeInteger<T extends number> = Integer<Negative<T>>;
export type NonZero<T extends number> = Exclude<T, 0 | -0>;
export type IsNonZero<T extends number> = T extends 0 | -0 ? false : true;
